trigger:
  paths:
    include:
      - sonos-s1-controller/*

extends:
  template: ../.azure-pipelines/templates/choco_pack_test_publish_nuget_package.yml
  parameters:
    packageLocation: repo://sonos-s1-controller
    packageName: sonos-s1-controller
    packageVersion: 57.3.77280
    pushToCommunityFeed: True