trigger:
  paths:
    include:
      - microsoft-office-click-to-run/*

extends:
  template: ../.azure-pipelines/templates/choco_build_and_publish_nuget_package.yml
  parameters:
    packageName: microsoft-office-click-to-run
    packageVersion: 1.0.0
    skipTest: true #testArgs: --params /configuration-xml-file:./microsoft-office-click-to-run/tools/configuration_install_example.xml
    pushToCommunityFeed: false
