trigger:
  paths:
    include:
      - microsoft-office-click-to-run/*

extends:
  template: ../.azure-pipelines/templates/choco_pack_test_publish_nuget_package.yml
  parameters:
    packageLocation: repo://microsoft-office-click-to-run
    packageName: microsoft-office-click-to-run
    packageVersion: 1.0.1
    installArgs: --params /configuration-xml-file:$(Build.SourcesDirectory)\microsoft-office-click-to-run\tools\configuration_install_example.xml
    pushToCommunityFeed: False