trigger:
  paths:
    include:
      - microsoft-office-deployment-tool/*

extends:
  template: ../.azure-pipelines/templates/choco_build_and_publish_nuget_package.yml
  parameters:
    packageName: microsoft-office-deployment-tool
    packageVersion: 16.0.12827.20258
    pushToCommunityFeed: true